#==============================================================
#
#  Abs: Generate IOCs Archive list  
#
#  Facility: FACET-II Oscilloscope Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (LUCHINI)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#          comment
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
# Install archive list into $TOP/archive
ARCHIVE += sioc-sys1-sc01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


