#==============================================================
#
#  Abs: Common Archive templates
#
#  Facility: EED Oscilloscope Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (LUCHINI)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#          comment
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
ARCHIVE += $(IOCADMIN)/archive/archive_iocAdmin.archive

# Install archive list into $TOP/archive
#ARCHIVE += tds.tpl-arch

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


