#==============================================================
#
#  Abs: Generate IOCs Archive list  
#
#  Facility: LCLS Oscilloscope Controls
#
#  Auth: 06-Mar-2019, Kristi Luchini  (LUCHINI)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        09-Apr-2021, K. Luchini      (LUCHINI):
#         install sioc-sys0-sc01.archive
#
#============================================================== 
#
TOP = ../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
# Install archive list into $TOP/archive
ARCHIVE += sioc-lgun-sc01.archive
ARCHIVE += sioc-sys0-sc01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


